export const NAK = Symbol('nats:nak');
export const TERM = Symbol('nats:term');

export const DEFAULT_NAK_DELAY = 1000;
export const DEFAULT_MAX_NAK_DELAY = 60000;

export const NATS_CONNECTION_DRAINING_ERROR_CODE = 'CONNECTION_DRAINING';
export const NATS_AUTHORIZATION_VIOLATION_ERROR_CODE = 'AUTHORIZATION_VIOLATION';

export const AUTHORIZATION_VIOLATION_RETRY_DELAY = 5000;
